"""YouTube Python SDK — async client for the YouTube Data API v3
and YouTube Analytics API.

Quick-start::

    from youtube import YouTubeClient, VideoPart, PrivacyStatus

    async with YouTubeClient(access_token="...") as yt:
        # List popular videos
        response = await yt.videos.list(
            parts=[VideoPart.SNIPPET, VideoPart.STATISTICS],
            chart="mostPopular",
        )

        # Upload a video
        from youtube import Video, VideoSnippet, VideoStatus
        video = await yt.videos.insert(
            body=Video(
                snippet=VideoSnippet(title="My Video", description="Hello!"),
                status=VideoStatus(privacy_status=PrivacyStatus.PRIVATE),
            ),
            file_path="/path/to/video.mp4",
        )
"""

__version__ = "0.1.0"

from youtube.client import YouTubeClient
from youtube.exceptions import (
    YouTubeAPIError,
    YouTubeAuthError,
    YouTubeBadRequestError,
    YouTubeConfigError,
    YouTubeConflictError,
    YouTubeForbiddenError,
    YouTubeNotFoundError,
    YouTubeQuotaExceededError,
    YouTubeRateLimitError,
    YouTubeSDKError,
    YouTubeServerError,
    YouTubeUploadError,
)
from youtube.models import (
    # analytics
    AnalyticsResponse,
    AudioTrackType,
    AuthorChannelId,
    Caption,
    CaptionFormat,
    CaptionListResponse,
    CaptionPart,
    CaptionSnippet,
    Channel,
    ChannelBannerResource,
    ChannelBrandingChannel,
    ChannelBrandingImage,
    ChannelBrandingSettings,
    ChannelContentDetails,
    ChannelListResponse,
    ChannelPart,
    ChannelRelatedPlaylists,
    ChannelSection,
    ChannelSectionContentDetails,
    ChannelSectionListResponse,
    ChannelSectionPart,
    ChannelSectionSnippet,
    ChannelSectionType,
    ChannelSnippet,
    ChannelStatistics,
    ChannelStatus,
    ChannelTopicDetails,
    ColumnHeader,
    Comment,
    CommentListResponse,
    CommentPart,
    CommentSnippet,
    CommentThread,
    CommentThreadListResponse,
    CommentThreadOrder,
    CommentThreadPart,
    CommentThreadReplies,
    CommentThreadSnippet,
    EventType,
    Localization,
    ModerationStatus,
    PageInfo,
    Playlist,
    PlaylistContentDetails,
    PlaylistItem,
    PlaylistItemContentDetails,
    PlaylistItemListResponse,
    PlaylistItemPart,
    PlaylistItemSnippet,
    PlaylistItemStatus,
    PlaylistListResponse,
    PlaylistPart,
    PlaylistPlayer,
    PlaylistSnippet,
    PlaylistStatus,
    PrivacyStatus,
    Rating,
    ResourceId,
    SafeSearch,
    SearchListResponse,
    SearchOrder,
    SearchPart,
    SearchResult,
    SearchResultSnippet,
    SearchResultType,
    SubscriberSnippet,
    Subscription,
    SubscriptionContentDetails,
    SubscriptionListResponse,
    SubscriptionOrder,
    SubscriptionPart,
    SubscriptionSnippet,
    TextFormat,
    Thumbnail,
    ThumbnailDetails,
    ThumbnailSetResponse,
    TrackKind,
    UploadStatus,
    Video,
    VideoCaption,
    VideoContentDetails,
    VideoDefinition,
    VideoDimension,
    VideoDuration,
    VideoGetRatingResponse,
    VideoLicense,
    VideoListResponse,
    VideoLiveStreamingDetails,
    VideoPart,
    VideoPlayer,
    VideoRating,
    VideoRecordingDetails,
    VideoSnippet,
    VideoStatistics,
    VideoStatus,
    VideoTopicDetails,
    VideoType,
    Watermark,
    WatermarkCornerPosition,
    WatermarkPosition,
    WatermarkTiming,
    WatermarkTimingType,
    YouTubeBaseModel,
)
from youtube.oauth import (
    GOOGLE_TOKEN_ENDPOINT,
    OAuthClient,
    TokenResponse,
)

__all__ = [
    # client
    "YouTubeClient",
    # oauth
    "GOOGLE_TOKEN_ENDPOINT",
    "OAuthClient",
    "TokenResponse",
    # exceptions
    "YouTubeAPIError",
    "YouTubeAuthError",
    "YouTubeBadRequestError",
    "YouTubeConfigError",
    "YouTubeConflictError",
    "YouTubeForbiddenError",
    "YouTubeNotFoundError",
    "YouTubeQuotaExceededError",
    "YouTubeRateLimitError",
    "YouTubeSDKError",
    "YouTubeServerError",
    "YouTubeUploadError",
    # base model
    "YouTubeBaseModel",
    # common
    "Localization",
    "PageInfo",
    "PrivacyStatus",
    "ResourceId",
    "Thumbnail",
    "ThumbnailDetails",
    # videos
    "Rating",
    "UploadStatus",
    "Video",
    "VideoContentDetails",
    "VideoGetRatingResponse",
    "VideoLicense",
    "VideoListResponse",
    "VideoLiveStreamingDetails",
    "VideoPart",
    "VideoPlayer",
    "VideoRating",
    "VideoRecordingDetails",
    "VideoSnippet",
    "VideoStatistics",
    "VideoStatus",
    "VideoTopicDetails",
    # channels
    "Channel",
    "ChannelBrandingChannel",
    "ChannelBrandingImage",
    "ChannelBrandingSettings",
    "ChannelContentDetails",
    "ChannelListResponse",
    "ChannelPart",
    "ChannelRelatedPlaylists",
    "ChannelSnippet",
    "ChannelStatistics",
    "ChannelStatus",
    "ChannelTopicDetails",
    # playlists
    "Playlist",
    "PlaylistContentDetails",
    "PlaylistListResponse",
    "PlaylistPart",
    "PlaylistPlayer",
    "PlaylistSnippet",
    "PlaylistStatus",
    # playlist items
    "PlaylistItem",
    "PlaylistItemContentDetails",
    "PlaylistItemListResponse",
    "PlaylistItemPart",
    "PlaylistItemSnippet",
    "PlaylistItemStatus",
    # comments
    "AuthorChannelId",
    "Comment",
    "CommentListResponse",
    "CommentPart",
    "CommentSnippet",
    "ModerationStatus",
    "TextFormat",
    # comment threads
    "CommentThread",
    "CommentThreadListResponse",
    "CommentThreadOrder",
    "CommentThreadPart",
    "CommentThreadReplies",
    "CommentThreadSnippet",
    # subscriptions
    "SubscriberSnippet",
    "Subscription",
    "SubscriptionContentDetails",
    "SubscriptionListResponse",
    "SubscriptionOrder",
    "SubscriptionPart",
    "SubscriptionSnippet",
    # thumbnails
    "ThumbnailSetResponse",
    # search
    "EventType",
    "SafeSearch",
    "SearchListResponse",
    "SearchOrder",
    "SearchPart",
    "SearchResult",
    "SearchResultSnippet",
    "SearchResultType",
    "VideoCaption",
    "VideoDefinition",
    "VideoDimension",
    "VideoDuration",
    "VideoType",
    # captions
    "AudioTrackType",
    "Caption",
    "CaptionFormat",
    "CaptionListResponse",
    "CaptionPart",
    "CaptionSnippet",
    "TrackKind",
    # channel sections
    "ChannelSection",
    "ChannelSectionContentDetails",
    "ChannelSectionListResponse",
    "ChannelSectionPart",
    "ChannelSectionSnippet",
    "ChannelSectionType",
    # channel banners
    "ChannelBannerResource",
    # watermarks
    "Watermark",
    "WatermarkCornerPosition",
    "WatermarkPosition",
    "WatermarkTiming",
    "WatermarkTimingType",
    # analytics
    "AnalyticsResponse",
    "ColumnHeader",
]
